# Classify a set of segmented clusters of a point cloud
# author: Aitor Aldoma, aldoma@acin.tuwien.ac.at
# author: Michael Zillich, zillich@acin.tuwien.ac.at

# the original full view organized point cloud
sensor_msgs/PointCloud2 cloud

---

# model ids of recognized objects
std_msgs/String[] ids

# 3D poses of recognized objects
geometry_msgs/Transform[] transforms
