# Start a new incremental segmentation cycle
# author: Michael Zillich, zillich@acin.tuwien.ac.at

# the full view organized point cloud
sensor_msgs/PointCloud2 cloud

# 2D saliency map image of same size as organized point cloud
sensor_msgs/Image saliency_map

---
