## joint_names
#joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint]
joint_names: [joint1, joint2, joint3, joint4, joint5]
## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
#
joint_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  constraints:
    goal_time: 10.0
    stopped_velocity_tolerance: 0.1
  gains:
    joint1: {p: 30, d: 0.5, i: 0, i_clamp: 1}
    joint2: {p: 30, d: 0.5, i: 0, i_clamp: 1}
    joint3: {p: 30, d: 0.5, i: 0, i_clamp: 1}
    joint4: {p: 30, d: 0.5, i: 0, i_clamp: 1}
    joint5: {p: 30, d: 0.5, i: 0, i_clamp: 1}


