sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CATKIN_WS_UNDERLAY=~/catkin_ws_underlay
    - CATKIN_WS_UNDERLAY_SRC=${CATKIN_WS_UNDERLAY}/src
    - CI_ROS_DISTRO="indigo"
    - ROS_PARALLEL_JOBS=-j1
    #- DEFAULT_ROSINSTALL=".travis.rosinstall"

install:
  - sudo sh -c 'echo "deb http://doc.openrobotino.org/download/packages/amd64 ./" >> /etc/apt/sources.list'
  - sudo apt-get update -qq
  - sudo apt-key update
  - sudo apt-get -q -y --force-yes install robotino-api2
  - bash .travis.sh
