# Manipulation action messages: BLINDGRASP

# goal definition
geometry_msgs/Pose heap_center_pose
geometry_msgs/Point heap_bounding_box
sensor_msgs/PointCloud heap_point_cloud
---
# result definition
string result_status
float32 stability
---
#feedback
string current_phase
string current_status
int32 percent_completed
