# Manipulation action messages: PICKUP

# goal definition
string object_id
string next_manipulation
---
# result definition
string result_status
float32 stability
---
#feedback
string current_phase
string current_status
int32 percent_completed
