<?xml version="1.0"?>
<root xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="hokuyo" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 -0.05" rpy="0 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://robotino_description/meshes/RobotinoLaserScanner.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${HOKUYO_LENGTH/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${HOKUYO_RADIUS}" length="${HOKUYO_LENGTH}" />
        </geometry>
      </collision>
    </link>
    
    <!-- gazebo extensions -->
    <xacro:hokuyo_gazebo name="${name}" ros_topic="scan" update_rate="10" min_angle="-2.2689" max_angle="2.2689"/>
    
  </xacro:macro>

  <!--GAZEBO PLUGIN-->
  <xacro:macro name="hokuyo_gazebo" params="name ros_topic update_rate min_angle max_angle">
    <gazebo reference="${name}_link">
      <sensor name="${name}" type="ray">
        <always_on>true</always_on>
        <update_rate>${update_rate}</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>640</samples>
              <resolution>1.0</resolution>
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.05</min>
            <max>10.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.005</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_${name}_controller" filename="libgazebo_ros_laser.so">
          <topicName>${ros_topic}</topicName>
          <frameName>${name}_link</frameName>
        </plugin>
      </sensor>
      <material>Gazebo/White</material>
    </gazebo>
  </xacro:macro>

  
</root>
