# Goal consists of target value and control method
string joint_name
float64 new_setpoint
bool joint_effort_control_enabled
bool track_now
---
# Result consists of a status report
float64 joint_angle
float64 joint_effort
string joint_status
---
# Feedback consists of current joint state
float64 joint_angle
float64 joint_effort
string joint_status
