# Goal consists of max joint velocity
string joint_name
float64 joint_max_velocity
bool set_now
---
# Result consists of a status report
float64 joint_current_max_velocity
string joint_status
---
# Feedback consists of current joint max velocity
float64 joint_current_max_velocity
string joint_status
