# Object perception action definition
# author: Markus Bajones (bajo), bajones@acin.tuwien.ac.at

# goal definition
# check for object = 0, classify and recognize objects = 1
int32 look_for_object
# use with look_for_object = 0
string id
string category
geometry_msgs/Pose pose
---
# result definition
string result_status
---
# feedback definition
string current_phase
string current_status
int32 percent_completed
